### ISSUE TITLE
[HELP] Using Superjson with React Native(Expo) & tRPC

### ISSUE THREAD

**Issue by NoneWofie** [blitz-js/superjson#192] opened 2022-07-11 06:55 UTC
Hi, I'm trying to implement trpc into React Native and was adding superjson as a transformer. However I couldn't get it to work and can't find any online.

tRPC works, I can query my backend.

Problem
![image](https://user-images.githubusercontent.com/70955773/178205727-2a539d09-90fd-4ea7-8955-1ebd5e381287.png)

Adding superjson to trpc client.
![image](https://user-images.githubusercontent.com/70955773/178205866-ef4900e7-8f2d-4130-9c75-c01ebafc6c46.png)

package.json file
`{
	"name": "frontend",
	"version": "1.0.0",
	"main": "./src/App.tsx",
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject"
	},
	"dependencies": {
		"@trpc/client": "^9.25.3",
		"@trpc/react": "^9.25.3",
		"backend": "1.0.0",
		"expo": "~45.0.0",
		"expo-status-bar": "~1.3.0",
		"react": "17.0.2",
		"react-dom": "17.0.2",
		"react-native": "0.68.2",
		"react-native-web": "0.17.7",
		"react-query": "^3.39.1",
		"superjson": "^1.9.1"
	},
	"devDependencies": {
		"@babel/core": "^7.12.9",
		"@types/react": "~17.0.21",
		"@types/react-native": "~0.66.13",
		"typescript": "~4.3.5"
	},
	"private": true
}
`

**Comment by Skn0tt** [comment] 2022-07-11 08:03
I think this is a duplicate of https://github.com/blitz-js/superjson/issues/190#issuecomment-1139603553. Closing for now, feel free to re-open if that doesn't help.

**Closed by Skn0tt** 2022-07-11 08:03 UTC

**Comment by NoneWofie** [comment] 2022-07-11 09:24
Hi, it works! thank you <3
